version: "3.9"
services:
  mongo_db:
    container_name: cefcom_mongo
    image: mongo:latest
    restart: always
    networks:
      - main_net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    container_name: cefcom_backend
    build:
      context: ./server
    restart: always
    networks:
      - main_net
    environment:
      PORT: 5000
      MONGODB_SERVER: cefcom_mongo
      MONGODB_SERVER_STATIC: localhost
      MONGODB_URI: mongodb//mongo_db:27017,
      JWT_SECRET: skfjslkjksdfjw3434j32l4
      JWT_EXPIRES_IN: 36000
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_db

networks:
  main_net:
    driver: bridge

volumes:
  mongo-data: {}