version: "3.9"
services:
  mongo_db:
    container_name: cefcom_mongo
    image: mongo:latest
    restart: always
    networks:
      - main_net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    container_name: cefcom_backend
    build:
      context: ./server
    restart: always
    networks:
      - main_net
    environment:
      PORT: 5000
      MONGODB_SERVER: cefcom_mongo
      MONGODB_SERVER_STATIC: localhost
      MONGODB_URI: mongodb//mongo_db:27017,
      JWT_SECRET: skfjslkjksdfjw3434j32l4
      JWT_EXPIRES_IN: 365d
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_db

  frontend:
    container_name: cefcom_frontend
    build:
      context: ./client
    restart: always
    networks:
      - main_net
    environment:
      NODE_ENV: dev
      BACKEND_SERVER: cefcom_backend
      BACKEND_PORT: 5000
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

networks:
  main_net:
    driver: bridge

volumes:
  mongo-data: {}