version: "3"
services:
  backend:
    build:
      context: ./server
    env_file: ./server/config/dev.env
    ports:
      - "5000:5000"
    networks:
      - main-net
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - main-net
    volumes:
      - mongo-data:/data/db
networks:
  main-net:
    driver: bridge
volumes:
  mongo-data:
    driver: local